include:
    - PinLayout

exclude:
    - PinLayoutTests
    - PinLayoutSample
    - Carthage
    - Source/Pods
    - data
    - scripts

except:
    - trailing-whitespace
    - brace-style
    - function-whitespace
    - terminating-semicolon
    - lower-camel-case
    - trailing-closure
    - forced-type-cast
