language: objective-c
osx_image: xcode8.3
xcode_project: PinLayout.xcodeproj
xcode_scheme: PinLayout
xcode_sdk: iphonesimulator9.3
env:
  global: 
before_install:
  #- brew update
  #- brew install tailor
  - gem install xcpretty-travis-formatter
  - carthage bootstrap --platform iOS
  
script: xcodebuild
  -project  PinLayout.xcodeproj
  -scheme "PinLayout"
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6'
  -enableCodeCoverage YES 
  test
 | xcpretty -f `xcpretty-travis-formatter`

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'PinLayout' -J 'PinLayoutTests'